import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import MobileNav from "@/components/shared/MobileNav";
import { NavbarDemo } from "@/components/shared/Navbar";
import Image from "next/image";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex justify-between ">
          <h1 className="text-2xl md:text-3xl font-bold text-white absolute top-6 left-3 lg:left-20 flex justify-center z-10">
            SM <span className="text-orange-400 pl-1">Cabins</span>
          </h1>
          <MobileNav />
        </div>
        <NavbarDemo />
        {children}
      </body>
    </html>
  );
}
